# Generated by Django 4.2.30 on 2026-05-14 20:12

from django.db import migrations, models


def blank_emails_to_null(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(blank_emails_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
