# Generated by Django 4.2.30 on 2026-05-14 20:14

import core.apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.apps.users.models.UserManager()),
            ],
        ),
    ]
