# Generated by Django 4.2.29 on 2026-04-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymob_order_id', models.CharField(blank=True, max_length=100)),
                ('paymob_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_key', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('VOIDED', 'Voided'), ('FAILED', 'Failed')], default='AUTHORIZED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment', to='orders.order')),
            ],
        ),
    ]
